### PR TITLE
Esp32 modbus experimental

### PR DESCRIPTION
**Pull request by DGrebe**
Hi Stuart,

I have implemented basic Modbus functionality an an own page to read Modbus powermeters (other devices are possible).  I can merge your last changes, but want to get your feedback and see if you are interessed and we have a common goal.

**Description**
- Modbus page showing the channels.  (currently two meters with 5 measurements each: energy, power, voltage, current, frequency. 
- Reading intervall can be configured (min)
- Current setup is based on SDM120 meters based on the library from reaper7, others should work as well, as long as they are using float values
- Currently hardware Serial2 is used for reading - reaper7 said, that the esp32 lib should not be used with SW serial. I haven't tried it.

**Todo**
- save and read modbus configuration to and from eprom
- add measures from modbus to rules page - to be discussed how to best do this
- rewrite into modbus class
- publishing to MQTT and InfluxDB
- close button on modbus config page not working
- Update selected line in modbus table after save setting
- value based trigger logic for publishing and including a maximum time, when nothing is changes. parameter is available, but not active, as it only makes sense with the trigger logic

**Discussion Points**
- how to add the modbus channels flagged for rules to the rules logic, what is the priority
- decoupling of elements - I tried to decouple what was possible, but am not very experienced in C++ and classes. As an example I though about putting part of the DIYBMSserver methods to the Modbus source/ class, but then I missed information.
- where to put the modbus reading. It is currently in the main loop but might be better with an own timer. For my purposes especially the inverters output voltage is critical and should be checked frequently

grafik

### CODE REVIEW

**Comment by stuartpittaway** [comment]
Thank you for this change.  I was just about to start looking at modbus on the ESP32.

I have the necessary controller hardware/pcb sorted out now, so can concentrate on the software side of things.

I also have an Eastron SDM230-modbus meter which I can use for testing, and the new diybms current shunt will also be RS485/modbus based.

A lot of the ESP32 code needs to be re-written to move into the RTOS timer architecture the ESP32 supports.

**Comment by stuartpittaway** [comment]
I'm not very happy with the SDM library - it has too many hardcoded #defines in it, may need to look at a rewrite or modification for that.

**Comment by atanisoft** [comment]
@stuartpittaway I believe IDF has a modbua client component

**Comment by DGrebe** [comment]
Hi Stuart,

I also don’t like parts of it, especially the „SDM_Config_User.h“ logic.

Overall the new joint definition of the register codes is very good.
One could bring this into the DIYBMSController to make it more user friendly.

I can rewrite parts of the library, if required. Let me know what you think.

Regards
Dirk

**Comment by stuartpittaway** [comment]
Hi Dirk, thanks for the submission, its a good idea.

What is the thoughts around these fields, how do you see them working?

Min duration (s)  60
Max duration (s) 3600


I think we will need to move to a generic ModBus library that can talk to several different devices on the RS485 bus.

**Comment by DGrebe** [comment]
Hi Stuart,

The min duration is the period, in which the modbus values are read. This works.

The max duration should be used for the distribution of values via MQTT / InfluxDB:
If the value has not changed (significantly), it will be send again after the max period.

Regards,

Dirk

**Comment by stuartpittaway** [comment]
Ok, so probably need to look at how this works from a timer/task perspective, probably changing "min" to "interval" or similar.

**Comment by DGrebe** [comment]
Interval is fine for me.

Currently I can chose the interval per Stream / Measurement.
In my example, the voltage is critical and should be read often, the Energy is uncritical as no rules will depend on it.

I am not sure, If one can have one timer/task per measurement.

I am willing to support a more flexible approach for the modbus queries.
I think one has to differentiate between sensors and actors.
The actors will react on rules, the sensors will provide input for rules.

Cheers

Dirk

**Pull request merged**
