### PR TITLE
Modbus routines

### PR DESCRIPTION
**Pull request by DGrebe**
- added new modbus read / write routines, independently of SDM lib
- added types for reading (byte, word, long, float) - I could only test float due to my device

### CODE REVIEW

**Comment by stuartpittaway** [comment]
Hi, I've not had chance to take a look at this change yet, real work getting in the way :-)

**Comment by DGrebe** [comment]
Not a problem, take your time.

What is the modbus shunt you are using?
I could have a look into the docs and configure it.

Cheers
Dirk

**Comment by stuartpittaway** [comment]
The shunt is my own design, not finished yet

**Comment by stuartpittaway** [comment]
Hello, do we need to use uint32_t for the timing values?  It uses up a lot of RAM which is in short supply on these microcontrollers.

What purpose does the description do?  Do we need this - again for RAM considerations?

The baud rate for RS485 could also be moved into the JSON file.

**Comment by DGrebe** [comment]
Hi Stuart, 
- Description is just for convenience. I think, the length of the fields can be halved 
MODBUS_NAME_LEN 11
MODBUS_UNIT_LEN 4
MODBUS_DESC_LEN 20
- Idea behind the timestamps was to reduce network traffic. If RAM is critical, take it out. 
- Baud Rate can go to the JSON file. Maybe we should put the comms parameter (8N1) in there as well.

Should I do the adjustments?
Should I look for further RAM enhancements?
The JSON documents are not RAM optimized from my point of view as well, maybe one would use dynamic allocated RAM.

Do you have any idea how to bring the new „Modbus“ rules in? How many would you see? Where would this fit in by sequence? 
The critical one I see is, that the inverter voltage should be in a given range (e.e. 225 - 235 V) to switch my load to this inverter instead of the grid.
If the inverter voltage is not good enough, I would run the load from the grid.


Regards

Dirk


27.01.2021 11:07:12 Stuart Pittaway <notifications@github.com>:


Hello, do we need to use uint32_t for the timing values? It uses up a lot of RAM which is in short supply on these microcontrollers.

What purpose does the description do? Do we need this - again for RAM considerations?

The baud rate for RS485 could also be moved into the JSON file.

**Pull request closed without merging**
